### ISSUE TITLE
CA Root certificate should be configurable

### ISSUE THREAD

**Issue by jamesc** [opscode/chef-analytics#4]
If you use your own certificates, we assume that they are rooted by a CA in the [Mozilla CACERT bundle](http://curl.haxx.se/docs/caextract.html).

If you use your own internal CA then you'll see SSL failures in actions_messages (usually something like `certify: tls_connection.erl:375:Fatal error: unknown ca`

We should allow to set the CA root cert in `opscode-analytics.rb`

**Comment by PrajaktaPurohit** [comment]
https://github.com/opscode/omnibus-analytics/pull/168
